---
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
environment:
  nodejs_version: '9'
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> package.json
install:
  - ps: Install-Product node $env:nodejs_version x64
  - choco install -y gpg4win
  - gpg --import test/fixtures/gpg.key
  - yarn
test_script:
  - yarn test --coverage
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
